language: java
jdk:
  - oraclejdk8
notifications:
  slack:
    secure: "Zqs/hjgAO5KBWr689NyfIIqfiQbObDqpPLmZypZbH/aTrUUPeTRp7qS2kUajezTa97lbZO/NPtmyr9a/ziJK/VfuZaQ7SFGH38/5QHdU836uqEQeKoLWLIaNwnS1OqvtADbkR2Lg16kJaXMtPz2mWMzPs77JnIqj8ijkMwmDUVU8Emh4+VGSkJK28ebVe8waVaIG8ClTmGCwpzVcsbe5qJ6GEiTSvZC/skyCMSUCjJ0YK7QDNTlAl6P5RII4ly4HKG7gm/BTTvoyHYKWZBvOEiE51cpQmPDIWV15miyriDSWU0MQST7znZRz0RL9EM0F4Ht9OpF5sR09LIQpKL6pDGanfGt/OqtLEX62g++QOltD5i6WSGAA3bHfllWeUkMvUdlc7rFDrpzH34eOemvlByIoeWst0sGyxXJ0Bx4gM9GDNbLoKW6lw8B/zvZrtdiTOYOGYSuxPwVGQESg0LGdE+H/js+Lr7DeOYOK78LMoIRBDXAzA/CIjKsFksMJN4POnXq9MLm81YCQ+v15+XnVruiyyhKFhY9bmE1Pt51Eoq+HC4XUeb50U4ACIZXw6yXBO1pn+sqiHgI5fLXO8CTavWN7DmVPjACYyX1iJI4lNFPdGWS7BUvOTspJQkPhRMpmV1+NandXbacH8F8wSmwFCGDDNt5wJBw2EMb7l4Xmgto="
