language: java
jdk:
  - oraclejdk8
notifications:
  slack:
    secure: "drqfdvxS2OSc7x4AHoZwOp+J33NvU0XK8V1heWuVf7lf2nNNyAMieWuqPZS7W4CF1gIfAvvZ+O9jkOyXD9zOzN4YhwmMzaUwrZbLPs6kB98sQE3qjynV9l/F06DxGVI0WiSe5YhAv3HM7IyAc+4WDhe/b/LPu6wjYsYGPGYCJ16iWjjZVj7A2Sa0fAmtYTCuzkoWfD079P/ltXu5lA0bPsiw5uB9wPNJ5X0D0VgJarkZ3SmULbLlsca1zMbH2O7R8fojfntXYDicw3ctlAPsXRiDVpC+W+GzPVP3OYYbB6OX9OnUqbatdylRH5biDP41SLnHkta9Rt6/owxCIjN9JeVaUbjestOUiovEFlcfrNM7fgCWwB/L5G24YKptHK4Ly2cC2gotw/HJgtfir185DYZG/bFwyKIcl7MdFw+224O6SCIYAXPs8qNF3lfr3yG47Ikbeh8C6Lp3eYQlO2hbdSxhavousaM6jSbFaFUGWzG4Q354bemhrp08RBAwrsa+6nQTmlflc/awaogbJSGODpOtwA/5Yf5bqXCppbA75Q1LLcxRpMEbXR5d1FRvt733Auvq0l4Q4qeTjOmLUcI6qEKx8wxmC+ddyFC7iHLFXtiJMwXSnEx2rgzP8ypKkHHLUK3lH3wEENcqEPJIKeLRxF4n3BW2qDRAi19XDeziDEM="
