language: java
jdk:
  - oraclejdk8
notifications:
  slack:
    secure: "kg7vgONTk9BffyI+LnPqIGgcmxOPb78AQbxfykEY/T/UH+a5YOPoClzCQG8Qe9QZSiDVVC60NUjpCXME1HzMrrXSnvQM6Og7919xnjrUJFHy200cPRv5pX6vpk3irakkYtbXFamTnm5pOoVA/a6qwHpu/493+f7P6PmrvA+oLKtnpAvKrQ0xy3rxiCwicji5mbdo7EHAvEgqEkJeS+kyJ3BlDi5Xq1gwxOZEsMp6IDzXEB7igVApl1gFUrgUyrWPY8m8TLyRFSfyjzbpBtkylYyivxyhvpnx2phZ0S4TEBOj4K73Mifc9CIPMordNYcnzORNdJ0PyWmBUk3DlHUHVX0jJZOD3ivEGlv9pSWhnj3KxGyE8PB1GakXXrFwISogWyNqU+C/wh3DmbZrL+rUsaQ0rnIMypvcEp4TQETsbSFOu4aevVY8HLrPxMQLPtIaavhLppXXphQgesGsfQdR0pH1ebmH1Yom0Y9IH/X72kvT+FPWmcBsyyG2qeNpmHxELV+TDRYeIMttgUGDh1duDvzinALIZNISAH2EGESy5mvFxT9PpD0z/+LtX1YKPaLr4JVJuNA+nSiBITdnw2N09ivDSzOQ2h0y08E6k2gJaP99TmiCQ4sScnpCtPYOgdDLgnl9yHAFXSYkVawHA7UVIaoUZjfXXGcu9nDJrB2FPYg="
