/*
 * Copyright 2017 junichi11.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.junichi11.netbeans.modules.textlint.options;

import java.io.File;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.filesystems.FileUtil;
import org.openide.util.NbBundle;

final class TextlintOptionsPanel extends javax.swing.JPanel {

    private static final String TEXTLINT_LAST_FOLDER_SUFFIX = ".textlint"; // NOI18N
    private static final String TEXTLINTRC_LAST_FOLDER_SUFFIX = ".textlintrc"; // NOI18N
    private static final long serialVersionUID = -7873059711550842158L;

    private final TextlintOptionsPanelController controller;

    TextlintOptionsPanel(TextlintOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO add listeners
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textlintPathLabel = new javax.swing.JLabel();
        textlintPathTextField = new javax.swing.JTextField();
        textlintrcPathLabel = new javax.swing.JLabel();
        textlintrcPathTextField = new javax.swing.JTextField();
        textlintOptionsLabel = new javax.swing.JLabel();
        textlintOptionsTextField = new javax.swing.JTextField();
        textlintHtmlCheckBox = new javax.swing.JCheckBox();
        textlintPathBrowsButton = new javax.swing.JButton();
        textlintrcPathBrowsButton = new javax.swing.JButton();
        textlintRefreshOnSaveCheckBox = new javax.swing.JCheckBox();
        textlintShowAnnotationsCheckBox = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(textlintPathLabel, org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintPathLabel.text")); // NOI18N

        textlintPathTextField.setText(org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintPathTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(textlintrcPathLabel, org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintrcPathLabel.text")); // NOI18N

        textlintrcPathTextField.setText(org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintrcPathTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(textlintOptionsLabel, org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintOptionsLabel.text")); // NOI18N

        textlintOptionsTextField.setText(org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintOptionsTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(textlintHtmlCheckBox, org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintHtmlCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(textlintPathBrowsButton, org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintPathBrowsButton.text")); // NOI18N
        textlintPathBrowsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlintPathBrowsButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(textlintrcPathBrowsButton, org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintrcPathBrowsButton.text")); // NOI18N
        textlintrcPathBrowsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlintrcPathBrowsButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(textlintRefreshOnSaveCheckBox, org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintRefreshOnSaveCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(textlintShowAnnotationsCheckBox, org.openide.util.NbBundle.getMessage(TextlintOptionsPanel.class, "TextlintOptionsPanel.textlintShowAnnotationsCheckBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textlintrcPathLabel)
                    .addComponent(textlintPathLabel)
                    .addComponent(textlintOptionsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textlintrcPathTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(textlintPathTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textlintrcPathBrowsButton)
                            .addComponent(textlintPathBrowsButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(textlintOptionsTextField)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textlintHtmlCheckBox)
                    .addComponent(textlintRefreshOnSaveCheckBox)
                    .addComponent(textlintShowAnnotationsCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textlintPathLabel)
                    .addComponent(textlintPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textlintPathBrowsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textlintrcPathLabel)
                    .addComponent(textlintrcPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textlintrcPathBrowsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textlintOptionsLabel)
                    .addComponent(textlintOptionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textlintHtmlCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textlintRefreshOnSaveCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textlintShowAnnotationsCheckBox))
        );
    }// </editor-fold>//GEN-END:initComponents

    @NbBundle.Messages("TextlintOptionsPanel.browse.textlint.title=Select textlint script")
    private void textlintPathBrowsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlintPathBrowsButtonActionPerformed
        File textlint = new FileChooserBuilder(TextlintOptionsPanel.class.getName() + TEXTLINT_LAST_FOLDER_SUFFIX)
                .setTitle(Bundle.TextlintOptionsPanel_browse_textlint_title())
                .setFilesOnly(true)
                .showOpenDialog();
        if (textlint != null) {
            textlint = FileUtil.normalizeFile(textlint);
            String textlintPath = textlint.getAbsolutePath();
            textlintPathTextField.setText(textlintPath);
        }
    }//GEN-LAST:event_textlintPathBrowsButtonActionPerformed

    @NbBundle.Messages("TextlintOptionsPanel.browse.textlintrc.title=Select .textlintrc")
    private void textlintrcPathBrowsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlintrcPathBrowsButtonActionPerformed
        File textlintrc = new FileChooserBuilder(TextlintOptionsPanel.class.getName() + TEXTLINTRC_LAST_FOLDER_SUFFIX)
                .setTitle(Bundle.TextlintOptionsPanel_browse_textlintrc_title())
                .setFilesOnly(true)
                .showOpenDialog();
        if (textlintrc != null) {
            textlintrc = FileUtil.normalizeFile(textlintrc);
            String textlintrcPath = textlintrc.getAbsolutePath();
            textlintrcPathTextField.setText(textlintrcPath);
        }
    }//GEN-LAST:event_textlintrcPathBrowsButtonActionPerformed

    void load() {
        TextlintOptions options = TextlintOptions.getInstance();
        textlintPathTextField.setText(options.getTextlintPath());
        textlintrcPathTextField.setText(options.getTextlintrcPath());
        textlintOptionsTextField.setText(options.getTextlintOptions());
        textlintHtmlCheckBox.setSelected(options.isHtmlEnabled());
        textlintRefreshOnSaveCheckBox.setSelected(options.refreshOnSave());
        textlintShowAnnotationsCheckBox.setSelected(options.showAnnotation());
    }

    void store() {
        TextlintOptions options = TextlintOptions.getInstance();
        options.setTextlintPath(textlintPathTextField.getText().trim());
        options.setTextlintrcPath(textlintrcPathTextField.getText().trim());
        options.setTextlintOptions(textlintOptionsTextField.getText().trim());
        options.setHtmlEnabled(textlintHtmlCheckBox.isSelected());
        options.setRefreshOnSave(textlintRefreshOnSaveCheckBox.isSelected());
        options.setShowAnnotation(textlintShowAnnotationsCheckBox.isSelected());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox textlintHtmlCheckBox;
    private javax.swing.JLabel textlintOptionsLabel;
    private javax.swing.JTextField textlintOptionsTextField;
    private javax.swing.JButton textlintPathBrowsButton;
    private javax.swing.JLabel textlintPathLabel;
    private javax.swing.JTextField textlintPathTextField;
    private javax.swing.JCheckBox textlintRefreshOnSaveCheckBox;
    private javax.swing.JCheckBox textlintShowAnnotationsCheckBox;
    private javax.swing.JButton textlintrcPathBrowsButton;
    private javax.swing.JLabel textlintrcPathLabel;
    private javax.swing.JTextField textlintrcPathTextField;
    // End of variables declaration//GEN-END:variables
}
